#!/usr/bin/csh
set test_name = "$1"
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+fifo_vip/verif/sequences +incdir+fifo_vip/verif/test +incdir+fifo_vip/verif/top +incdir+fifo_vip/verif/fifo_uvc ./rtl/fifo.sv ./fifo_vip/verif/top/fifo_top.sv -l fifo_compile.log +define+9_7
./simv +UVM_TIMEOUT=5000000 -l fifo_sim0.log
